### ISSUE TITLE
Future of WP AJAX Edit Comments

### ISSUE THREAD

**Issue by dancameron** [mihdan/ajax-edit-comments#6]
Here's the plan I have initially setup for the future of AEC:

1. Roll through all the issues and push out a release soon.
2. Start a complete re-write in a few months; re-write will bring the plugin back to something minimal.
3. Start building up the plugin to the same feature set that it has now.

The idea of # 2 will be to build a solid foundation; something that we can build upon so that new features can be easily added.

## QA

**Why adopt this plugin**
I've been looking for a popular plugin to adopt for quite some time now, AEC is one that could use a lot of work and I'm okay with taking on that challenge.

**Will there be a Premium Version like other Sprout Apps**
I can't say "no" but I doubt it. I didn't adopt this plugin to build a premium version. I adopted it so I can give back to the WP community in a different way than I have already. What would be more likely is that we sell premium add-ons...which I can't imagine any existing for a straight-forward plugin like AEC.

**What do I mean by "something minimal"**
I think the feature set for AEC is a bit bloated, maybe some of the features within AEC are required for some of it's users, that's why I'm asking all AEC users to tell me which features AEC must keep. I'll create a new issue soon to have that conversation.

## More

**Anything I missed?**

**Comment by ronalfy** [comment]
Most users who switch from AEC to Simple Comment Editing tell me they hated the colorbox pop-ups for editing comments.

I originally coded AEC just like Simple Comment Editing, to have inline editing.  The problem was, back in like 2007 when I coded it, a page with 300 comments would cause a jQuery selector timeout.  Also, people complained about the comment section being messed up with all the extra mark-up and such, so a lightbox solution was used to make the plugin pretty much theme independent.

I'm not sure if you want to go back to an inline approach, but I know a lot of people would love that, or a better lightbox modal that works well on mobile would be a huge plus.

One of the most requested features for Simple Comment Editing has been the ability to delete their own comments.  People coming over from AEC absolutely miss this feature.

**Comment by dancameron** [comment]
Thanks @ronalfy for the history and feedback.

It's very likely, almost certain, that I'll go back to inline editing. I too like the ability to delete their own comments and will make that a phase 1 feature.
